version: 2.1

jobs:

  search_build:
    docker:
    - image: google/cloud-sdk
    steps:
    - checkout
    - setup_remote_docker

    - run:
        name: Setup Google Cloud SDK
        command: |
          apt-get install -qq -y gettext
          echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json
          gcloud auth activate-service-account --key-file=gcloud-service-key.json
          ls -l
    - run:
        name: docker gcloud init
        command: |
          gcloud auth configure-docker  us-central1-docker.pkg.dev

    - run:
        name: Build and Push Search Service
        command: |
          docker build -t us-central1-docker.pkg.dev/codetokloud/search/search:latest ./services/search
          docker push us-central1-docker.pkg.dev/codetokloud/search/search:latest

  search_deploy:
    docker:
    - image: google/cloud-sdk:latest
    steps:
    - checkout
    - run:
        name: Authenticate with GKE
        command: |
          echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json
          gcloud auth activate-service-account --key-file=gcloud-service-key.json
          gcloud config set project codetokloud
          gcloud container clusters get-credentials cluster-1 --zone us-central1
    - run:
        name: Install Helm
        command: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - run:
        name: Deploy Search Service
        command: |
          helm upgrade --install search ./helm/search --set image.repository=us-central1-docker.pkg.dev/codetokloud/search/search:latest --set image.tag=latest


workflows:
  version: 2
  search_build_and_deploy:
    jobs:
    - search_build
    - search_deploy:
        requires:
        - search_build
        filters:
            branches:
              only: main